workflows:
  ios-workflow:
    name: iOS Build & Upload
    environment:
      vars:
        XCODE_WORKSPACE: "Huldrivox.xcodeproj"  # or .xcodeproj if no CocoaPods
        XCODE_SCHEME: "Huldrivox"
      xcode: latest
    scripts:
      - name: Build IPA
        script: |
          xcodebuild clean -workspace $XCODE_WORKSPACE -scheme $XCODE_SCHEME -configuration Release -sdk iphoneos -archivePath $HOME/build/$XCODE_SCHEME.xcarchive archive
          xcodebuild -exportArchive -archivePath $HOME/build/$XCODE_SCHEME.xcarchive -exportOptionsPlist ExportOptions.plist -exportPath $HOME/build
    artifacts:
      - build/*.ipa
    publishing:
      app_store_connect:
        api_key:
          key_id: "XCY285TMQC"
          issuer_id: "31b49898-e13f-4731-ad0e-289331700376"
          private_key: "-----BEGIN PRIVATE KEY-----MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgu+3Gm8rExlbRSxLZJgeDgQdfG+OGjfhmBelH/SRkVNagCgYIKoZIzj0DAQehRANCAARXtg3wOEOAByQYugFdL/Zg/J1OpRj/LvznAochkfZuZ2UHxE0OjXg92hb/JEyAdLSk+f0SktjTzE4hKDNMz+3D-----END PRIVATE KEY-----"
