workflows:
  ios-workflow:
    name: iOS App Store Build
    environment:
      groups:
        - admin
      vars:
        XCODE_PROJECT: "Huldrivox/Huldrivox.xcodeproj"
        XCODE_SCHEME: "Huldrivox"
    scripts:
      - name: Initialize keychain
        script: |
          keychain initialize

      - name: Decode and import signing certificate
        script: |
          echo $CERTIFICATE_PRIVATE_KEY | base64 --decode > certificate.p12
          security import certificate.p12 -P "$CERTIFICATE_PASSWORD" -A

      # Optional: Only if automatic signing still requires a profile
      - name: Import provisioning profile (optional)
        script: |
          echo $PROVISIONING_PROFILE | base64 --decode > profile.mobileprovision
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp profile.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/

      - name: Build IPA using automatic signing
        script: |
          xcode-project build-ipa \
            --project "$XCODE_PROJECT" \
            --scheme "$XCODE_SCHEME"

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM

    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
