workflows:
  ios-manual-signing:
    name: iOS App Store Build (Manual Signing)
    environment:
      groups:
        - admin
      vars:
        XCODE_PROJECT: "Huldrivox/Huldrivox.xcodeproj"
        XCODE_SCHEME: "Huldrivox"
        DEVELOPMENT_TEAM: "URFBLTLN99"
        CODE_SIGN_IDENTITY: "Apple Distribution" # Change to Apple Distribution if required
    scripts:
      - name: Initialize keychain
        script: |
          keychain initialize

      - name: Import distribution certificate
        script: |
          echo $CERTIFICATE_PRIVATE_KEY | base64 --decode > certificate.p12
          security import certificate.p12 -P "$CERTIFICATE_PASSWORD" -A

      - name: Import provisioning profile
        script: |
          echo $PROVISIONING_PROFILE | base64 --decode > profile.mobileprovision
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          security cms -D -i profile.mobileprovision > decoded.plist
          uuid=$(/usr/libexec/PlistBuddy -c "Print UUID" decoded.plist)

          if [ -z "$uuid" ]; then
            echo "❌ Failed to extract UUID from provisioning profile"
            cat decoded.plist
            exit 1
          fi

          cp profile.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/$uuid.mobileprovision

      - name: Generate export options plist
        script: |
          cat > export_options.plist <<EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>method</key>
              <string>app-store</string>
              <key>teamID</key>
              <string>${DEVELOPMENT_TEAM}</string>
              <key>signingStyle</key>
              <string>manual</string>
              <key>provisioningProfiles</key>
              <dict>
                  <key>com.Huldrivox</key>
                  <string>Huldrivox</string>
              </dict>
              <key>compileBitcode</key>
              <true/>
              <key>destination</key>
              <string>export</string>
              <key>stripSwiftSymbols</key>
              <true/>
              <key>thinning</key>
              <string>&lt;none&gt;</string>
          </dict>
          </plist>
          EOF

      - name: Set up manual code signing
        script: |
          xcode-project use-profiles

      - name: Build IPA with manual signing
        script: |
          xcode-project build-ipa \
            --project "$XCODE_PROJECT" \
            --scheme "$XCODE_SCHEME" \
            --export-options-plist export_options.plist
            --export-xcargs "CODE_SIGN_IDENTITY='iPhone Distribution: Adeline Lee (URFBLTLN99)'"

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM

    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
