workflows:
  ios-workflow:
    name: Custom Workflow
    environment:
      groups:
        - admin
      vars:
        XCODE_PROJECT: "Huldrivox.xcodeproj"
        XCODE_SCHEME: "Huldrivox"
      code_signing:
        provisioning_profiles: auto
    scripts:
      - name: Set up keychain for code signing
        script: keychain initialize

      - name: Fetch signing files
        script: app-store-connect fetch-signing-files "com.huldrivox"

      - name: Set up signing certificate
        script: keychain add-certificates

      - name: Set up code signing in project
        script: xcode-project use-profiles

      - name: Build App
        script: xcode-project build-ipa --xcodeproj "$XCODE_PROJECT" --scheme "$XCODE_SCHEME"

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM

    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_ID
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
